import jspf.compiler.syntax as syntax

def test_pass_syntax():
    prog = r'  ^.[foo]./bar\d+/(?!./baz/).(.{7, ..., 15}|.{100, 105, 110})' +\
           r'(?=./qux/+).*?<.$/^[h-y]+-\d\d$/>'
    tree = syntax.pass_syntax(prog)
    assert tree.to_dict() == {
       "Node.S":[
          {
             "Node.A":[
                {
                   "Node.T":[
                      {
                         "TokenType.ROOT":"^"
                      }
                   ]
                },
                {
                   "Node.C":[
                      
                   ]
                }
             ]
          },
          {
             "Node.Q":[
                
             ]
          },
          {
             "Node.E":[
                {
                   "Node.A":[
                      {
                         "Node.T":[
                            {
                               "TokenType.NAV":"."
                            }
                         ]
                      },
                      {
                         "Node.C":[
                            {
                               "TokenType.STR_MATCH":"[foo]"
                            }
                         ]
                      }
                   ]
                },
                {
                   "Node.Q":[
                      
                   ]
                },
                {
                   "Node.E":[
                      {
                         "Node.A":[
                            {
                               "Node.T":[
                                  {
                                     "TokenType.NAV":"."
                                  }
                               ]
                            },
                            {
                               "Node.C":[
                                  {
                                     "TokenType.REGEX":"/bar\\d+/"
                                  }
                               ]
                            }
                         ]
                      },
                      {
                         "Node.Q":[
                            
                         ]
                      },
                      {
                         "Node.E":[
                            {
                               "Node.A":[
                                  {
                                     "TokenType.NONCAP_NEG_BEGIN":"(?!"
                                  },
                                  {
                                     "Node.S":[
                                        {
                                           "Node.A":[
                                              {
                                                 "Node.T":[
                                                    {
                                                       "TokenType.NAV":"."
                                                    }
                                                 ]
                                              },
                                              {
                                                 "Node.C":[
                                                    {
                                                       "TokenType.REGEX":"/baz/"
                                                    }
                                                 ]
                                              }
                                           ]
                                        },
                                        {
                                           "Node.Q":[
                                              
                                           ]
                                        },
                                        {
                                           "Node.E":[
                                              
                                           ]
                                        }
                                     ]
                                  },
                                  {
                                     "Node.U":[
                                        
                                     ]
                                  },
                                  {
                                     "TokenType.NONCAP_NEG_END":")"
                                  }
                               ]
                            },
                            {
                               "Node.Q":[
                                  
                               ]
                            },
                            {
                               "Node.E":[
                                  {
                                     "Node.A":[
                                        {
                                           "Node.T":[
                                              {
                                                 "TokenType.NAV":"."
                                              }
                                           ]
                                        },
                                        {
                                           "Node.C":[
                                              
                                           ]
                                        }
                                     ]
                                  },
                                  {
                                     "Node.Q":[
                                        
                                     ]
                                  },
                                  {
                                     "Node.E":[
                                        {
                                           "Node.A":[
                                              {
                                                 "TokenType.CAP_BEGIN":"("
                                              },
                                              {
                                                 "Node.S":[
                                                    {
                                                       "Node.A":[
                                                          {
                                                             "Node.T":[
                                                                {
                                                                   "TokenType.NAV":"."
                                                                }
                                                             ]
                                                          },
                                                          {
                                                             "Node.C":[
                                                                {
                                                                   "TokenType.SET_MATCH":"{7, ..., 15}"
                                                                }
                                                             ]
                                                          }
                                                       ]
                                                    },
                                                    {
                                                       "Node.Q":[
                                                          
                                                       ]
                                                    },
                                                    {
                                                       "Node.E":[
                                                          
                                                       ]
                                                    }
                                                 ]
                                              },
                                              {
                                                 "Node.U":[
                                                    {
                                                       "TokenType.UNION":"|"
                                                    },
                                                    {
                                                       "Node.S":[
                                                          {
                                                             "Node.A":[
                                                                {
                                                                   "Node.T":[
                                                                      {
                                                                         "TokenType.NAV":"."
                                                                      }
                                                                   ]
                                                                },
                                                                {
                                                                   "Node.C":[
                                                                      {
                                                                         "TokenType.SET_MATCH":"{100, 105, 110}"
                                                                      }
                                                                   ]
                                                                }
                                                             ]
                                                          },
                                                          {
                                                             "Node.Q":[
                                                                
                                                             ]
                                                          },
                                                          {
                                                             "Node.E":[
                                                                
                                                             ]
                                                          }
                                                       ]
                                                    }
                                                 ]
                                              },
                                              {
                                                 "TokenType.CAP_END":")"
                                              }
                                           ]
                                        },
                                        {
                                           "Node.Q":[
                                              
                                           ]
                                        },
                                        {
                                           "Node.E":[
                                              {
                                                 "Node.A":[
                                                    {
                                                       "TokenType.NONCAP_POS_BEGIN":"(?="
                                                    },
                                                    {
                                                       "Node.S":[
                                                          {
                                                             "Node.A":[
                                                                {
                                                                   "Node.T":[
                                                                      {
                                                                         "TokenType.NAV":"."
                                                                      }
                                                                   ]
                                                                },
                                                                {
                                                                   "Node.C":[
                                                                      {
                                                                         "TokenType.REGEX":"/qux/"
                                                                      }
                                                                   ]
                                                                }
                                                             ]
                                                          },
                                                          {
                                                             "Node.Q":[
                                                                {
                                                                   "TokenType.DEFAULT_EXIST":"+"
                                                                }
                                                             ]
                                                          },
                                                          {
                                                             "Node.E":[
                                                                
                                                             ]
                                                          }
                                                       ]
                                                    },
                                                    {
                                                       "Node.U":[
                                                          
                                                       ]
                                                    },
                                                    {
                                                       "TokenType.NONCAP_POS_END":")"
                                                    }
                                                 ]
                                              },
                                              {
                                                 "Node.Q":[
                                                    
                                                 ]
                                              },
                                              {
                                                 "Node.E":[
                                                    {
                                                       "Node.A":[
                                                          {
                                                             "Node.T":[
                                                                {
                                                                   "TokenType.NAV":"."
                                                                }
                                                             ]
                                                          },
                                                          {
                                                             "Node.C":[
                                                                
                                                             ]
                                                          }
                                                       ]
                                                    },
                                                    {
                                                       "Node.Q":[
                                                          {
                                                             "TokenType.LAZY_ANY":"*?"
                                                          }
                                                       ]
                                                    },
                                                    {
                                                       "Node.E":[
                                                          {
                                                             "Node.A":[
                                                                {
                                                                   "TokenType.SELECT_BEGIN":"<"
                                                                },
                                                                {
                                                                   "Node.S":[
                                                                      {
                                                                         "Node.A":[
                                                                            {
                                                                               "Node.T":[
                                                                                  {
                                                                                     "TokenType.NAV":"."
                                                                                  }
                                                                               ]
                                                                            },
                                                                            {
                                                                               "Node.C":[
                                                                                  
                                                                               ]
                                                                            }
                                                                         ]
                                                                      },
                                                                      {
                                                                         "Node.Q":[
                                                                            
                                                                         ]
                                                                      },
                                                                      {
                                                                         "Node.E":[
                                                                            {
                                                                               "Node.A":[
                                                                                  {
                                                                                     "Node.T":[
                                                                                        {
                                                                                           "TokenType.VAL":"$"
                                                                                        }
                                                                                     ]
                                                                                  },
                                                                                  {
                                                                                     "Node.C":[
                                                                                        {
                                                                                           "TokenType.REGEX":"/^[h-y]+-\\d\\d$/"
                                                                                        }
                                                                                     ]
                                                                                  }
                                                                               ]
                                                                            },
                                                                            {
                                                                               "Node.Q":[
                                                                                  
                                                                               ]
                                                                            },
                                                                            {
                                                                               "Node.E":[
                                                                                  
                                                                               ]
                                                                            }
                                                                         ]
                                                                      }
                                                                   ]
                                                                },
                                                                {
                                                                   "Node.U":[
                                                                      
                                                                   ]
                                                                },
                                                                {
                                                                   "TokenType.SELECT_END":">"
                                                                }
                                                             ]
                                                          },
                                                          {
                                                             "Node.Q":[
                                                                
                                                             ]
                                                          },
                                                          {
                                                             "Node.E":[
                                                                
                                                             ]
                                                          }
                                                       ]
                                                    }
                                                 ]
                                              }
                                           ]
                                        }
                                     ]
                                  }
                               ]
                            }
                         ]
                      }
                   ]
                }
             ]
          }
       ]
    }
